/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.Crear;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ordenador
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private String rutaDirectorios;
    private int controlador;
    private ActionEvent evt;
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bnDirectorios = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bnArchivos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        bnOcultos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bnRegresar = new javax.swing.JButton();
        jLModificacion = new javax.swing.JLabel();
        jLRuta = new javax.swing.JLabel();
        jLTamaño = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        txtNuevoArchivo = new javax.swing.JMenuItem();
        txtNuevaCarpeta = new javax.swing.JMenuItem();
        txtRenombrar = new javax.swing.JMenuItem();
        txtEliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Archivos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        bnDirectorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnDirectoriosMouseClicked(evt);
            }
        });
        bnDirectorios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bnDirectoriosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(bnDirectorios);

        jLabel1.setText("Directorios");

        bnArchivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bnArchivosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(bnArchivos);

        bnOcultos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bnOcultosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(bnOcultos);

        jLabel2.setText("Archivos");

        jLabel3.setText("Ocultos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)))
                .addGap(7, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3)
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));
        getContentPane().add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 180, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ruta");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        bnRegresar.setText("Regresar");
        bnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(bnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLModificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLModificacion.setForeground(new java.awt.Color(0, 255, 255));
        jLModificacion.setText("Fecha de modificacion:");
        getContentPane().add(jLModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLRuta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLRuta.setForeground(new java.awt.Color(0, 255, 255));
        jLRuta.setText("Ruta absoluta");
        getContentPane().add(jLRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLTamaño.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTamaño.setForeground(new java.awt.Color(0, 255, 255));
        jLTamaño.setText("Tamaño (Kb):");
        getContentPane().add(jLTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/Crear/3.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -4, 420, 520));

        jMenu1.setText("Archivos");

        txtNuevoArchivo.setText("Nuevo archivo");
        txtNuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(txtNuevoArchivo);

        txtNuevaCarpeta.setText("Nueva carpeta");
        txtNuevaCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaCarpetaActionPerformed(evt);
            }
        });
        jMenu1.add(txtNuevaCarpeta);

        txtRenombrar.setText("Renombrar");
        txtRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRenombrarActionPerformed(evt);
            }
        });
        jMenu1.add(txtRenombrar);

        txtEliminar.setText("Eliminar");
        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(txtEliminar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnDirectoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnDirectoriosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            String archivoSeleccionado = (String)bnDirectorios.getSelectedValue();
            txtRuta.setText(txtRuta.getText()+ "\\" + archivoSeleccionado);
                btnBuscarActionPerformed(this.evt);
            }
    }//GEN-LAST:event_bnDirectoriosMouseClicked

    private void bnDirectoriosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bnDirectoriosValueChanged
        // TODO add your handling code here:
        controlador=0;
        bnArchivos.clearSelection();
        bnOcultos.clearSelection();
        String elementoSeleccionado = (String) bnDirectorios.getSelectedValue();
        String rutaSeleccionada = txtRuta.getText().trim() +"\\" + elementoSeleccionado; 
        File fichero= new File(rutaSeleccionada);
        long fechaMilisegundo= fichero.lastModified();
        Date fecha= new Date(fechaMilisegundo);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yy");
        jLModificacion.setText(formato.format(fecha));
        jLRuta.setText(fichero.getAbsolutePath());
        jLTamaño.setText(""+ fichero.length() / 1024);
        //bnDirectorios.clearSelection();
        bnOcultos.clearSelection();
    }//GEN-LAST:event_bnDirectoriosValueChanged

    private void bnArchivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bnArchivosValueChanged
        // TODO add your handling code here:
        controlador =0;
        String elementoSeleccionado = (String) bnArchivos.getSelectedValue();
        String rutaSeleccionada = txtRuta.getText().trim() +"\\" + elementoSeleccionado; 
        File fichero= new File(rutaSeleccionada);
        long fechaMilisegundo= fichero.lastModified();
        Date fecha= new Date(fechaMilisegundo);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yy");
        jLModificacion.setText(formato.format(fecha));
        jLRuta.setText(fichero.getAbsolutePath());
        jLTamaño.setText(""+ fichero.length() / 1024);
        bnDirectorios.clearSelection();
        bnOcultos.clearSelection();
    }//GEN-LAST:event_bnArchivosValueChanged

    private void bnOcultosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bnOcultosValueChanged
        // TODO add your handling code here:
        controlador=0;
        String elementoSeleccionado = (String) bnOcultos.getSelectedValue();
        String rutaSeleccionada = txtRuta.getText().trim() +"\\" + elementoSeleccionado; 
        File fichero = new File(rutaSeleccionada);
        long fechaMilisegundo= fichero.lastModified();
        Date fecha= new Date(fechaMilisegundo);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yy");
        jLModificacion.setText(formato.format(fecha));
        jLRuta.setText(fichero.getAbsolutePath());
        jLTamaño.setText(""+ fichero.length() / 1024);
        bnDirectorios.clearSelection();
        bnArchivos.clearSelection();
        //bnOcultos.clearSelection();
    }//GEN-LAST:event_bnOcultosValueChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.evt=evt;
        if(!txtRuta.getText().equals("")){

            File ruta= new File(txtRuta.getText());
            File[] archivos = ruta.listFiles();
            DefaultListModel model = new DefaultListModel();
            for(File archivo : archivos){
                if(archivo.isDirectory()){
                    model.addElement(archivo.getName());
                }
            }
            bnDirectorios.setModel(model);
            model = new DefaultListModel();
            for(File archivo : archivos){
                if(archivo.isFile()&&! archivo.isHidden()){
                    model.addElement(archivo.getName());
                }
            }
            bnArchivos.setModel(model);
            model = new DefaultListModel();
            for(File archivo : archivos){
                if(archivo.isHidden()){
                    model.addElement(archivo.getName());
                }
            }
            bnOcultos.setModel(model);
        }else{
            JOptionPane.showMessageDialog(this,"ingrese una ruta");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void bnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnRegresarActionPerformed
        // TODO add your handling code here:
        String nuevaRuta= null;
        for(int i= txtRuta.getText().length()-1; i>= 0; i--){
            if(txtRuta.getText().charAt(i) =='\\'){
                nuevaRuta =txtRuta.getText().substring(0,i);
                System.out.println(nuevaRuta);
                i=-1;
            }
        }
        txtRuta.setText(nuevaRuta);
        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_bnRegresarActionPerformed

    private void txtNuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoArchivoActionPerformed
        // TODO add your handling code here:
        String nombreArchivo = JOptionPane.showInputDialog("Ingrese el nombre del archivo:");
        String ruta ;
        if(controlador==0){
            ruta = txtRuta.getText() + "\\" + nombreArchivo;
        }else{
            ruta = rutaDirectorios + "\\" + nombreArchivo;
        }

        File archivoNuevo = new File(ruta);
        if (!archivoNuevo.exists()) {
            try {
                archivoNuevo.createNewFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Error: archivo no pudo ser creado");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Error: archivo ya existe");
        }

        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_txtNuevoArchivoActionPerformed

    private void txtNuevaCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaCarpetaActionPerformed
        // TODO add your handling code here:
        String nombreDirectorio = JOptionPane.showInputDialog("Ingresa el nombre de la nueva carpeta");
        String ruta;
        if(controlador==0){
            ruta=  txtRuta.getText().trim() + "\\" + nombreDirectorio;
        }else{
            ruta = rutaDirectorios + "\\" + nombreDirectorio;
        }
        File directorio = new File(ruta);
        if(!directorio.exists()){
            directorio.mkdir();

        }else{
            JOptionPane.showMessageDialog(this, "El directorio ya existe en la ruta");
        }
        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_txtNuevaCarpetaActionPerformed

    private void txtRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRenombrarActionPerformed
        // TODO add your handling code here:
        String archivoSeleccionado = null;
        if(!bnDirectorios.isSelectionEmpty()){
            archivoSeleccionado = (String) bnDirectorios.getSelectedValue();
        }else if(!bnArchivos.isSelectionEmpty()) {
            archivoSeleccionado = (String) bnArchivos.getSelectedValue();
        }else if(!bnOcultos.isSelectionEmpty()){
            archivoSeleccionado = (String) bnOcultos.getSelectedValue();
        }else {
            JOptionPane.showMessageDialog(this,"selecione");
        }

        String rutaArchivoSeleccionado = txtRuta.getText().trim() + "\\" + archivoSeleccionado;
        File archivo = new File(rutaArchivoSeleccionado);

        String nombreNuevoArchivo = JOptionPane.showInputDialog("Ingrese el nuevo nombre del archivo:");
        String rutaNuevoArchivo = txtRuta.getText().trim() + "\\" + nombreNuevoArchivo;
        File archivoNuevo = new File(rutaNuevoArchivo);

        if(!archivoNuevo.exists()){
            archivo.renameTo(archivoNuevo);
        }else{
            JOptionPane.showMessageDialog(this, "Ya existe un archivo con ese nombre");

        }

        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_txtRenombrarActionPerformed

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
        // TODO add your handling code here:
        String archivoSeleccionado = null;
        boolean isValid = true;

        if(!bnDirectorios.isSelectionEmpty()){
            archivoSeleccionado = (String) bnDirectorios.getSelectedValue();
        }else if(!bnArchivos.isSelectionEmpty()) {
            archivoSeleccionado = (String) bnArchivos.getSelectedValue();
        }else if(!bnOcultos.isSelectionEmpty()){
            archivoSeleccionado = (String) bnOcultos.getSelectedValue();
        }else {
            isValid = false;
            JOptionPane.showMessageDialog(this, " seleccionar");
        }

        if(isValid){

            String rutaArchivoSeleccionado = txtRuta.getText().trim() + "\\" + archivoSeleccionado;
            File archivo = new File(rutaArchivoSeleccionado);
            if(!archivo.isDirectory()){
                eliminarCarpeta(rutaArchivoSeleccionado);
            }else{
                archivo.delete();
            }

            btnBuscarActionPerformed(evt);
        }
    }//GEN-LAST:event_txtEliminarActionPerformed
    public void eliminarCarpeta(String ruta){
        File lista= new File(ruta);
        File[] archivos = lista.listFiles();
        for(File archivo: archivos){
            if(archivo.isDirectory()){
                eliminarCarpeta(ruta + "\\" + archivo.getName());
            }else{
                archivo.delete();
            }
        }
        lista.delete();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> bnArchivos;
    private javax.swing.JList<String> bnDirectorios;
    private javax.swing.JList<String> bnOcultos;
    private javax.swing.JButton bnRegresar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLModificacion;
    private javax.swing.JLabel jLRuta;
    private javax.swing.JLabel jLTamaño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem txtEliminar;
    private javax.swing.JMenuItem txtNuevaCarpeta;
    private javax.swing.JMenuItem txtNuevoArchivo;
    private javax.swing.JMenuItem txtRenombrar;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables

    private void listarArchivos(String trim) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
