/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.Crear;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ordenador
 */
public class Menu extends javax.swing.JInternalFrame {

    /**
     * Creates new forcm Menu
     */
    private directorios;
    private controlador;
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bnDirectorios = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bnArchivos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        bnOcultos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLModificacion = new javax.swing.JLabel();
        jLRuta = new javax.swing.JLabel();
        jLTamaño = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        txtNuevoArchivo = new javax.swing.JMenuItem();
        txtNuevaCarpeta = new javax.swing.JMenuItem();
        txtRenombrar = new javax.swing.JMenuItem();
        txtEliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Archivos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        bnDirectorios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        bnDirectorios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bnDirectoriosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(bnDirectorios);

        jLabel1.setText("Directorios");

        bnArchivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        bnArchivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bnArchivosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(bnArchivos);

        bnOcultos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        bnOcultos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bnOcultosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(bnOcultos);

        jLabel2.setText("Archivos");

        jLabel3.setText("Ocultos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addGap(57, 57, 57))
        );

        jLModificacion.setText("Fecha de modificacion:");

        jLRuta.setText("Ruta absoluta");

        jLTamaño.setText("Tamaño (Kb):");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaActionPerformed(evt);
            }
        });

        jLabel7.setText("Ruta");

        jMenu1.setText("Archivos");

        txtNuevoArchivo.setText("Nuevo archivo");
        txtNuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(txtNuevoArchivo);

        txtNuevaCarpeta.setText("Nueva carpeta");
        txtNuevaCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaCarpetaActionPerformed(evt);
            }
        });
        jMenu1.add(txtNuevaCarpeta);

        txtRenombrar.setText("Renombrar");
        txtRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRenombrarActionPerformed(evt);
            }
        });
        jMenu1.add(txtRenombrar);

        txtEliminar.setText("Eliminar");
        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(txtEliminar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLRuta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTamaño, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLModificacion, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLRuta)
                .addGap(18, 18, 18)
                .addComponent(jLModificacion)
                .addGap(18, 18, 18)
                .addComponent(jLTamaño)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaActionPerformed
        // TODO add your handling code here:
        File file = new File ("C:\\Users\\Ordenador");
        
    }//GEN-LAST:event_txtRutaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        File ruta= new File(txtRuta.getText());
        File[] archivos = ruta.listFiles();
        DefaultListModel model = new DefaultListModel();
        for(File archivo : archivos){
            if(archivo.isDirectory()){
                model.addElement(archivo.getName());
            }
        }
        bnDirectorios.setModel(model);
        model = new DefaultListModel();
        for(File archivo : archivos){
            if(archivo.isFile()&&! archivo.isHidden()){
                model.addElement(archivo.getName());
            }
        }
        bnArchivos.setModel(model);
        model = new DefaultListModel();
        for(File archivo : archivos){
            if(archivo.isHidden()){
                model.addElement(archivo.getName());
            }
        }
        bnOcultos.setModel(model);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void bnDirectoriosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bnDirectoriosValueChanged
        // TODO add your handling code here:
        controlador=0;
        bnArchivos.clearSelection();
        bnOcultos.clearSelection();
        String elementoSeleccionado = (String) bnDirectorios.getSelectedValue();
        String rutaSeleccionada = txtRuta.getText().trim() +"\\" + elementoSeleccionado; 
        File fichero= new File(rutaSeleccionada);
        long fechaMilisegundo= fichero.lastModified();
        Date fecha= new Date(fechaMilisegundo);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yy");
        jLModificacion.setText(formato.format(fecha));
        jLRuta.setText(fichero.getAbsolutePath());
        jLTamaño.setText(""+ fichero.length() / 1024);
        bnDirectorios.clearSelection();
        bnOcultos.clearSelection();
        
    }//GEN-LAST:event_bnDirectoriosValueChanged

    private void bnArchivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bnArchivosValueChanged
        // TODO add your handling code here:
        controlador =0;
        String elementoSeleccionado = (String) bnArchivos.getSelectedValue();
        String rutaSeleccionada = txtRuta.getText().trim() +"\\" + elementoSeleccionado; 
        File fichero= new File(rutaSeleccionada);
        long fechaMilisegundo= fichero.lastModified();
        Date fecha= new Date(fechaMilisegundo);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yy");
        jLModificacion.setText(formato.format(fecha));
        jLRuta.setText(fichero.getAbsolutePath());
        jLTamaño.setText(""+ fichero.length() / 1024);
        bnDirectorios.clearSelection();
        bnOcultos.clearSelection();
        
    }//GEN-LAST:event_bnArchivosValueChanged

    private void bnOcultosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bnOcultosValueChanged
        // TODO add your handling code here:
        String elementoSeleccionado = (String) bnOcultos.getSelectedValue();
        String rutaSeleccionada = txtRuta.getText().trim() +"\\" + elementoSeleccionado; 
        File fichero = new File(rutaSeleccionada);
        long fechaMilisegundo= fichero.lastModified();
        Date fecha= new Date(fechaMilisegundo);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yy");
        jLModificacion.setText(formato.format(fecha));
        jLRuta.setText(fichero.getAbsolutePath());
        jLTamaño.setText(""+ fichero.length() / 1024);
        bnDirectorios.clearSelection();
        bnOcultos.clearSelection();
        
    }//GEN-LAST:event_bnOcultosValueChanged

    private void txtNuevaCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaCarpetaActionPerformed
        // TODO add your handling code here:
       String nombreDirectorio = JOptionPane.showInputDialog("Ingresa el nombre de la nueva carpeta");
       String ruta = txtRuta.getText().trim() + "\\" + nombreDirectorio;
        File directorio = new File(ruta);
        if(directorio.exists()){
            JOptionPane.showMessageDialog(this, "El directorio ya existe en la ruta");            
        }else{
            directorio.mkdir();
        }
        listarArchivos(txtRuta.getText().trim());
        
    }//GEN-LAST:event_txtNuevaCarpetaActionPerformed

    private void txtRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRenombrarActionPerformed
        // TODO add your handling code here:
        String archivoSeleccionado = null;
        if(!bnArchivos.isSelectionEmpty()){
            archivoSeleccionado = (String) bnArchivos.getSelectedValue();
        }else if(!bnDirectorios.isSelectionEmpty()) {
            archivoSeleccionado = (String) bnDirectorios.getSelectedValue();
        }else {
            archivoSeleccionado = (String) bnOcultos.getSelectedValue();
        }
        
        String rutaArchivoSeleccionado = txtRuta.getText().trim() + "\\" + archivoSeleccionado;
        File archivo = new File(rutaArchivoSeleccionado);
        
        String nombreNuevoArchivo = JOptionPane.showInputDialog("Ingrese el nuevo nombre del archivo:");
        String rutaNuevoArchivo = txtRuta.getText().trim() + "\\" + nombreNuevoArchivo;
        File archivoNuevo = new File(rutaNuevoArchivo);
        
        if(archivoNuevo.exists()){
            JOptionPane.showMessageDialog(this, "Ya existe un archivo con ese nombre");            
        }else{
            archivo.renameTo(archivoNuevo);
        }
        
        listarArchivos(txtRuta.getText().trim());
        
    }//GEN-LAST:event_txtRenombrarActionPerformed

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
        // TODO add your handling code here:
        String archivoSeleccionado = null;
        boolean isValid = true;
        
        if(!bnArchivos.isSelectionEmpty()){
            archivoSeleccionado = (String) bnArchivos.getSelectedValue();
        }else if(!bnDirectorios.isSelectionEmpty()) {
            archivoSeleccionado = (String) bnDirectorios.getSelectedValue();
        }else if(!bnOcultos.isSelectionEmpty()){
            archivoSeleccionado = (String) bnOcultos.getSelectedValue();
        }else {
            isValid = false;
            JOptionPane.showMessageDialog(this, "No has seleccionado un archivo para eliminar");
        }
        
        if(isValid){
        
            String rutaArchivoSeleccionado = txtRuta.getText().trim() + "\\" + archivoSeleccionado;
            File archivo = new File(rutaArchivoSeleccionado);
            archivo.delete();
            listarArchivos(txtRuta.getText().trim());                
        }
        
    }//GEN-LAST:event_txtEliminarActionPerformed

    private void txtNuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoArchivoActionPerformed
        // TODO add your handling code here:
       String nombreArchivo = JOptionPane.showInputDialog("Ingrese el nombre del archivo:");
       String ruta = txtRuta.getText().trim() + "\\" + nombreArchivo;

        File archivoNuevo = new File(ruta);
        if (!archivoNuevo.exists()) {
            try {
                archivoNuevo.createNewFile();
            } catch (IOException ex) {
                System.err.println("Error: archivo no pudo ser creado");
            }
        }
        
        listarArchivos(txtRuta.getText().trim()); 
       
        
    }//GEN-LAST:event_txtNuevoArchivoActionPerformed
public void mostrarInformacionArchivoSeleccionado(String rutaSeleccionada) {
        //obtengo la fecha de ultima modificacion
        File archivoSeleccionado = new File(rutaSeleccionada);
        long fechaMilisegundos = archivoSeleccionado.lastModified();
        Date fecha = new Date(fechaMilisegundos);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fechaTexto = formato.format(fecha);
        jLModificacion.setText("Fecha de ultima modificacion: " + fechaTexto);

        //obtengo la ruta absoluta
        String rutaAbsoluta = archivoSeleccionado.getAbsolutePath();
        jLRuta.setText("Ruta absoluta: " + rutaAbsoluta);

        //obtengo el tamano del archivo en kb
        long tamanoEnBytes = archivoSeleccionado.length();
        long tamanoEnKBytes = tamanoEnBytes / 1024l;

        jLTamaño.setText("Tamaño (Kb): " + tamanoEnKBytes);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> bnArchivos;
    private javax.swing.JList<String> bnDirectorios;
    private javax.swing.JList<String> bnOcultos;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLModificacion;
    private javax.swing.JLabel jLRuta;
    private javax.swing.JLabel jLTamaño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem txtEliminar;
    private javax.swing.JMenuItem txtNuevaCarpeta;
    private javax.swing.JMenuItem txtNuevoArchivo;
    private javax.swing.JMenuItem txtRenombrar;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables

    private void listarArchivos(String trim) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
